### ISSUE TITLE
Unable to disable item Stacking

### ISSUE THREAD

**Issue by KleskReaver** [TastyChickenLegs/DropMoreLoot#1]
Hi bud

using Enable Stacking = false
doesn't seem to work, item stack size will still change to the specified multiplier number (1 to 5)
So it behaves likes the setting is = true

I could just use multiplier of 1 to achieve the same effect but I also use AzuMiscPatches mod which has a stack size change feature that you cannot disable but it has other things I like in it

For testing I did try uninstalling AzuMiscPatches just in case it might have been messing with your mod and forcing your multiplier to be enabled all the time but that was not the case

if you could look at this that would be great thanks!

**Comment by TastyChickenLegs** [comment]
Yea I am working on a fix.  If you set the multiplier to 1 and click the disable button it will turn off.
